apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: otel-agent
  name: otel-agent
spec:
  ports:
  - name: "8887"
    port: 8887
    targetPort: 8888
  - name: "14250"
    port: 14250
    targetPort: 14250
  - name: "14268"
    port: 14268
    targetPort: 14268
  - name: "55678"
    port: 55678
    targetPort: 55678
  - name: "4317"
    port: 4317
    targetPort: 4317
  - name: "9411"
    port: 9411
    targetPort: 9411
  - name: "1777"
    port: 1777
    targetPort: 1777
  - name: "55679"
    port: 55679
    targetPort: 55679
  - name: "13133"
    port: 13133
    targetPort: 13133
  selector:
    io.kompose.service: otel-agent
status:
  loadBalancer: {}
