apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: victoriametrics
  name: victoriametrics
spec:
  ports:
  - name: "8428"
    port: 8428
    targetPort: 8428
  - name: "8089"
    port: 8089
    targetPort: 8089
  - name: 8089-udp
    port: 8089
    protocol: UDP
    targetPort: 8089
  - name: "2003"
    port: 2003
    targetPort: 2003
  - name: 2003-udp
    port: 2003
    protocol: UDP
    targetPort: 2003
  - name: "4242"
    port: 4242
    targetPort: 4242
  selector:
    io.kompose.service: victoriametrics
status:
  loadBalancer: {}
